db2  connect to xip user xipdb2 using system

db2  "delete from xip_tradeinfo where xip_id='TOWN-F' and xip_tradcode='AC01'";
db2  "insert into xip_tradeinfo values('TOWN-F', 'AC01', '制卡通知', '1', 'B', '0', '')";
db2  "delete from xip_fixedconv where xip_id='TOWN-F' and xip_convlevel='T' and xip_trcode='AC01'";
db2  "insert into xip_fixedconv values('TOWN-F', 'I', 'T', 'AC01', 1, '1', '', '银行代码', 'N', -1, -1, '0', 0, 0, '', '', '', '1', '0650')";
db2  "insert into xip_fixedconv values('TOWN-F', 'I', 'T', 'AC01', 2, '1', '', '子银行代码', 'N', -1, -1, '0', 0, 0, '', '', '', '1', '0230')";
db2  "insert into xip_fixedconv values('TOWN-F', 'I', 'T', 'AC01', 3, '1', '', '系统标别', 'N', -1, -1, '0', 0, 0, '', '', '', '1', '1340')";
db2  "insert into xip_fixedconv values('TOWN-F', 'I', 'T', 'AC01', 4, '1', '', '报文ID', 'N', -1, -1, '0', 0, 0, '', '', '', '1', '1530')";
db2  "insert into xip_fixedconv values('TOWN-F', 'I', 'T', 'AC01', 5, '1', '', '交易网点', 'N', -1, -1, '0', 0, 0, '', '', '', '1', '0007')";
db2  "insert into xip_fixedconv values('TOWN-F', 'I', 'T', 'AC01', 6, '1', '', '交易柜员', 'N', -1, -1, '0', 0, 0, '', '', '', '1', '0011')";
db2  "insert into xip_fixedconv values('TOWN-F', 'I', 'T', 'AC01', 7, '1', '', '地区代码', 'N', -1, -1, '0', 0, 0, '', '', '', '1', '1016')";
db2  "insert into xip_fixedconv values('TOWN-F', 'I', 'T', 'AC01', 8, '1', '', '交易渠道', 'N', -1, -1, '0', 0, 0, '', '', '', '1', '1260')";
db2  "insert into xip_fixedconv values('TOWN-F', 'I', 'T', 'AC01', 9, '1', '', '商户号', 'N', -1, -1, '0', 0, 0, '', '', '', '1', '1157')";
db2  "insert into xip_fixedconv values('TOWN-F', 'I', 'T', 'AC01', 10, '1', '', '终端号', 'N', -1, -1, '0', 0, 0, '', '', '', '1', '0014')";
db2  "insert into xip_fixedconv values('TOWN-F', 'I', 'T', 'AC01', 11, '1', '', '交易日期', 'N', -1, -1, '0', 0, 0, '', '', '', '1', '0770')";
db2  "insert into xip_fixedconv values('TOWN-F', 'I', 'T', 'AC01', 12, '1', '', '交易流水', 'N', -1, -1, '0', 0, 0, '', '', '', '1', '0780')";
db2  "insert into xip_fixedconv values('TOWN-F', 'I', 'T', 'AC01', 13, '1', '', '产品类型', 'N', -1, -1, '0', 0, 0, '', '', '', '1', '1228')";
db2  "insert into xip_fixedconv values('TOWN-F', 'I', 'T', 'AC01', 14, '1', '', '卡类型', 'N', -1, -1, '0', 0, 0, '', '', '', '1', '122B')";
db2  "insert into xip_fixedconv values('TOWN-F', 'I', 'T', 'AC01', 15, '1', '', '制卡文件名称', 'N', -1, -1, '0', 0, 0, '', '', '', '1', '0830')";
db2  "insert into xip_fixedconv values('TOWN-F', 'I', 'T', 'AC01', 16, '1', '', '制卡数量', 'N', -1, -1, '0', 0, 0, '', '', '', '1', '0520')";
db2  "insert into xip_fixedconv values('TOWN-F', 'I', 'T', 'AC01', 17, '1', '', '优先级', 'N', -1, -1, '0', 0, 0, '', '', '', '1', '100A')";
db2  "insert into xip_fixedconv values('TOWN-F', 'I', 'T', 'AC01', 18, '1', '', '卡有效期', 'N', -1, -1, '0', 0, 0, '', '', '', '1', '0440')";
db2  "insert into xip_fixedconv values('TOWN-F', 'O', 'T', 'AC01', 1, '0', '1340', '系统标别', 'N', -1, -1, '0', 0, 0, '', '', '', '2', '')";
db2  "insert into xip_fixedconv values('TOWN-F', 'O', 'T', 'AC01', 2, '0', '1530', '报文ID', 'N', -1, -1, '0', 0, 0, '', '', '', '2', '')";
db2  "insert into xip_fixedconv values('TOWN-F', 'O', 'T', 'AC01', 3, '0', '103A', '卡系统日期', 'N', -1, -1, '0', 0, 0, '', '', '', '2', '')";
db2  "insert into xip_fixedconv values('TOWN-F', 'O', 'T', 'AC01', 4, '0', '103D', '卡系统流水', 'N', -1, -1, '0', 0, 0, '', '', '', '2', '')";
db2  "insert into xip_fixedconv values('TOWN-F', 'O', 'T', 'AC01', 5, '0', '0004', '处理结果代码', 'N', -1, -1, '0', 0, 0, '', '', '', '2', '')";
db2  "insert into xip_fixedconv values('TOWN-F', 'O', 'T', 'AC01', 6, '0', '0005', '处理结果信息', 'N', -1, -1, '0', 0, 0, '', '', '', '2', '')";
db2  "insert into xip_fixedconv values('TOWN-F', 'O', 'T', 'AC01', 7, '0', '1067', '制卡批次号', 'N', -1, -1, '0', 0, 0, '', '', '', '2', '')";
db2  "delete from xip_chnlroute where xip_id='TOWN-F' and xip_fromtrcode='AC01'";
db2  "insert into xip_chnlroute values('TOWN-F', 'AC01', 1, 'ROUTE', 'BCPT-T', 'AC01_01', '', '获取村镇IC卡制卡文件', 'N')";
db2  "delete from xip_tradeflow where xip_id='BCPT-T' and xip_flowcode='AC01_01'";
db2  "insert into xip_tradeflow values('BCPT-T', 'AC01_01', 1, 'CALL', 'libkftpflow.so', 'KFtpFlow', '', '')";
db2  "delete from xip_tradfuncio where xip_id='BCPT-T' and xip_flowcode='AC01_01' and xip_seq=1";
db2  "insert into xip_tradfuncio values('BCPT-T', 'AC01_01', 1, 1, '#TOWN-GETIC', 'P0020', 'I', 'ftpid')";
db2  "insert into xip_tradfuncio values('BCPT-T', 'AC01_01', 1, 2, '#', 'P0720', 'I', '是否执行所有Y-是N-否')";
db2  "insert into xip_chnlroute values('TOWN-F', 'AC01', 2, 'ROUTE', 'BCPT-T', 'AC01_02', '', '', 'N')";
db2  "delete from xip_tradeflow where xip_id='BCPT-T' and xip_flowcode='AC01_02'";
db2  "insert into xip_tradeflow values('BCPT-T', 'AC01_02', 1, 'CALL', 'libkftpflow.so', 'KFtpFlow', '', '')";
db2  "delete from xip_tradfuncio where xip_id='BCPT-T' and xip_flowcode='AC01_02' and xip_seq=1";
db2  "insert into xip_tradfuncio values('BCPT-T', 'AC01_02', 1, 3, '#TOWN-PUTIC', 'P0020', 'I', 'ftpid')";
db2  "insert into xip_tradfuncio values('BCPT-T', 'AC01_02', 1, 4, '#N', 'P0720', 'I', '是否执行所有Y-是N-否')";
db2  "insert into xip_tradeflow values('BCPT-T', 'AC01_02', 2, 'EVAL', 'P100A', '#N', '', '')";
db2  "insert into xip_tradeflow values('BCPT-T', 'AC01_02', 3, 'COMM', '1001-AC01', '', 'B', '制卡通知')";
db2  "delete from xip_xmlconv where xip_id='BCPT-T' and xip_convlevel='T' and xip_trcode='1001-AC01'";
db2  "delete from xip_xmlnodeattr where xip_id='BCPT-T' and xip_convlevel='T' and xip_trcode='1001-AC01'";
db2  "insert into xip_xmlconv values('BCPT-T', 'I', 'T', '1001-AC01', 0, '', 'BCP', 'BCP', 'N', '/BCP/*', 'R', 'M', 'N', '', 'N', 'N', 'N', '', 'NOT', '0', 0, 0, '', '', '', '0')";
db2  "insert into xip_xmlconv values('BCPT-T', 'I', 'T', '1001-AC01', 1, 'BCP', 'HEAD', 'HEAD', 'N', '/BCP/HEAD/*', 'M', 'M', 'N', '', 'N', 'N', 'N', '', 'UToG1', '0', 0, 0, '', '', '', '0')";
db2  "insert into xip_xmlconv values('BCPT-T', 'I', 'T', '1001-AC01', 2, 'HEAD', 'SysId', '系统标别', 'N', '/BCP/HEAD/SysId', 'B', 'M', 'N', '', 'N', 'N', 'N', '1340', 'UToG1', '0', 0, 0, '', '', '', '1')";
db2  "insert into xip_xmlconv values('BCPT-T', 'I', 'T', '1001-AC01', 3, 'HEAD', 'MsgId', '报文ID', 'N', '/BCP/HEAD/MsgId', 'B', 'M', 'N', '', 'N', 'N', 'N', '1530', 'UToG1', '0', 0, 0, '', '', '', '1')";
db2  "insert into xip_xmlconv values('BCPT-T', 'I', 'T', '1001-AC01', 4, 'HEAD', 'BcpDate', '卡系统日期', 'N', '/BCP/HEAD/BcpDate', 'B', 'M', 'N', '', 'N', 'N', 'N', '103A', 'UToG1', '0', 0, 0, '', '', '', '1')";
db2  "insert into xip_xmlconv values('BCPT-T', 'I', 'T', '1001-AC01', 5, 'HEAD', 'BcpTraceNo', '卡系统流水', 'N', '/BCP/HEAD/BcpTraceNo', 'B', 'M', 'N', '', 'N', 'N', 'N', '103D', 'UToG1', '0', 0, 0, '', '', '', '1')";
db2  "insert into xip_xmlconv values('BCPT-T', 'I', 'T', '1001-AC01', 6, 'HEAD', 'RspCode', '处理结果代码', 'N', '/BCP/HEAD/RspCode', 'B', 'M', 'N', '', 'N', 'N', 'N', '0004', 'UToG1', '0', 0, 0, '', '', '', '1')";
db2  "insert into xip_xmlconv values('BCPT-T', 'I', 'T', '1001-AC01', 7, 'HEAD', 'RspMsg', '处理结果信息', 'N', '/BCP/HEAD/RspMsg', 'B', 'M', 'N', '', 'N', 'N', 'N', '0005', 'UToG1', '0', 0, 0, '', '', '', '1')";
db2  "insert into xip_xmlconv values('BCPT-T', 'I', 'T', '1001-AC01', 8, 'BCP', 'MSG', 'MSG', 'N', '/BCP/MSG/*', 'M', 'M', 'N', '', 'N', 'N', 'N', '', 'UToG1', '0', 0, 0, '', '', '', '0')";
db2  "insert into xip_xmlconv values('BCPT-T', 'I', 'T', '1001-AC01', 9, 'MSG', 'BatchNo', '制卡批次号', 'N', '/BCP/MSG/BatchNo', 'B', 'M', 'N', '', 'N', 'N', 'N', '1067', 'UToG1', '0', 0, 0, '', '', '', '1')";
db2  "insert into xip_xmlconv values('BCPT-T', 'O', 'T', '1001-AC01', 0, '', 'BCP', 'BCP', 'N', '/BCP/*', 'R', 'M', 'N', '', 'N', 'N', 'N', '', 'NOT', '0', 0, 0, '', '', '', '0')";
db2  "insert into xip_xmlconv values('BCPT-T', 'O', 'T', '1001-AC01', 1, 'BCP', 'HEAD', 'HEAD', 'N', '/BCP/HEAD/*', 'M', 'M', 'N', '', 'N', 'N', 'N', '', 'G1ToU', '0', 0, 0, '', '', '', '0')";
db2  "insert into xip_xmlconv values('BCPT-T', 'O', 'T', '1001-AC01', 2, 'HEAD', 'BankId', '银行代码', 'N', '/BCP/HEAD/BankId', 'B', 'M', 'N', '', 'N', 'N', 'N', '0650', 'G1ToU', '0', 0, 0, '', '', '', '1')";
db2  "insert into xip_xmlconv values('BCPT-T', 'O', 'T', '1001-AC01', 3, 'HEAD', 'SubBankId', '子银行代码', 'N', '/BCP/HEAD/SubBankId', 'B', 'M', 'N', '', 'N', 'N', 'N', '0230', 'G1ToU', '0', 0, 0, '', '', '', '1')";
db2  "insert into xip_xmlconv values('BCPT-T', 'O', 'T', '1001-AC01', 4, 'HEAD', 'SysId', '系统标别', 'N', '/BCP/HEAD/SysId', 'B', 'M', 'N', '', 'N', 'N', 'N', '1340', 'G1ToU', '0', 0, 0, '', '', '', '1')";
db2  "insert into xip_xmlconv values('BCPT-T', 'O', 'T', '1001-AC01', 5, 'HEAD', 'MsgId', '报文ID', 'N', '/BCP/HEAD/MsgId', 'B', 'M', 'N', '', 'N', 'N', 'N', '1530', 'G1ToU', '0', 0, 0, '', '', '', '1')";
db2  "insert into xip_xmlconv values('BCPT-T', 'O', 'T', '1001-AC01', 6, 'HEAD', 'Brno', '交易网点', 'N', '/BCP/HEAD/Brno', 'B', 'M', 'N', '', 'N', 'N', 'N', '0007', 'G1ToU', '0', 0, 0, '', '', '', '1')";
db2  "insert into xip_xmlconv values('BCPT-T', 'O', 'T', '1001-AC01', 7, 'HEAD', 'Tel', '交易柜员', 'N', '/BCP/HEAD/Tel', 'B', 'M', 'N', '', 'N', 'N', 'N', '0011', 'G1ToU', '0', 0, 0, '', '', '', '1')";
db2  "insert into xip_xmlconv values('BCPT-T', 'O', 'T', '1001-AC01', 8, 'HEAD', 'AreaCode', '地区代码', 'N', '/BCP/HEAD/AreaCode', 'B', 'M', 'N', '', 'N', 'N', 'N', '1016', 'G1ToU', '0', 0, 0, '', '', '', '1')";
db2  "insert into xip_xmlconv values('BCPT-T', 'O', 'T', '1001-AC01', 9, 'HEAD', 'TxChnl', '交易渠道', 'N', '/BCP/HEAD/TxChnl', 'B', 'M', 'N', '', 'N', 'N', 'N', '1260', 'G1ToU', '0', 0, 0, '', '', '', '1')";
db2  "insert into xip_xmlconv values('BCPT-T', 'O', 'T', '1001-AC01', 10, 'HEAD', 'MchtId', '商户号', 'N', '/BCP/HEAD/MchtId', 'B', 'M', 'N', '', 'N', 'N', 'N', '1157', 'G1ToU', '0', 0, 0, '', '', '', '1')";
db2  "insert into xip_xmlconv values('BCPT-T', 'O', 'T', '1001-AC01', 11, 'HEAD', 'Tty', '终端号', 'N', '/BCP/HEAD/Tty', 'B', 'M', 'N', '', 'N', 'N', 'N', '0014', 'G1ToU', '0', 0, 0, '', '', '', '1')";
db2  "insert into xip_xmlconv values('BCPT-T', 'O', 'T', '1001-AC01', 12, 'HEAD', 'TransDate', '交易日期', 'N', '/BCP/HEAD/TransDate', 'B', 'M', 'N', '', 'N', 'N', 'N', '0770', 'G1ToU', '0', 0, 0, '', '', '', '1')";
db2  "insert into xip_xmlconv values('BCPT-T', 'O', 'T', '1001-AC01', 13, 'HEAD', 'TransNo', '交易流水', 'N', '/BCP/HEAD/TransNo', 'B', 'M', 'N', '', 'N', 'N', 'N', '0780', 'G1ToU', '0', 0, 0, '', '', '', '1')";
db2  "insert into xip_xmlconv values('BCPT-T', 'O', 'T', '1001-AC01', 14, 'BCP', 'MSG', 'MSG', 'N', '/BCP/MSG/*', 'M', 'M', 'N', '', 'N', 'N', 'N', '', 'G1ToU', '0', 0, 0, '', '', '', '0')";
db2  "insert into xip_xmlconv values('BCPT-T', 'O', 'T', '1001-AC01', 15, 'MSG', 'ProType', '产品类型', 'N', '/BCP/MSG/ProType', 'B', 'M', 'N', '', 'N', 'N', 'N', '1228', 'G1ToU', '0', 0, 0, '', '', '', '1')";
db2  "insert into xip_xmlconv values('BCPT-T', 'O', 'T', '1001-AC01', 16, 'MSG', 'FileName', '制卡文件名称', 'N', '/BCP/MSG/FileName', 'B', 'M', 'N', '', 'N', 'N', 'N', '0830', 'G1ToU', '0', 0, 0, '', '', '', '1')";
db2  "insert into xip_xmlconv values('BCPT-T', 'O', 'T', '1001-AC01', 17, 'MSG', 'Number', '制卡数量', 'N', '/BCP/MSG/Number', 'B', 'M', 'N', '', 'N', 'N', 'N', '0520', 'G1ToU', '0', 0, 0, '', '', '', '1')";
db2  "insert into xip_xmlconv values('BCPT-T', 'O', 'T', '1001-AC01', 18, 'MSG', 'CrdType', '卡类型', 'N', '/BCP/MSG/CrdType', 'B', 'M', 'N', '', 'N', 'N', 'N', '122B', 'G1ToU', '0', 0, 0, '', '', '', '1')";
db2  "insert into xip_xmlconv values('BCPT-T', 'O', 'T', '1001-AC01', 19, 'MSG', 'FilePrior', '优先级', 'N', '/BCP/MSG/FilePrior', 'B', 'M', 'N', '', 'N', 'N', 'N', '100A', 'G1ToU', '0', 0, 0, '', '', '', '1')";
db2  "insert into xip_xmlconv values('BCPT-T', 'O', 'T', '1001-AC01', 20, 'MSG', 'ExpDate', '卡有效期', 'N', '/BCP/MSG/ExpDate', 'B', 'M', 'N', '', 'N', 'N', 'N', '0440', 'G1ToU', '0', 0, 0, '', '', '', '1')";


db2 "delete from xip_tradeinfo where xip_id='TOWN-F' and xip_tradcode='SO02'";
db2 "insert into xip_tradeinfo values('TOWN-F', 'SO02', '新社保村镇回盘', '1', 'B', '3', '')";
db2 "delete from xip_fixedconv where xip_id='TOWN-F' and xip_convlevel='T' and xip_trcode='SO02'";
db2 "insert into xip_fixedconv values('TOWN-F', 'I', 'T', 'SO02', 1, '1', '', '版本', 'N', -1, -1, '0', 0, 0, '', '', '', '1', '0580')";
db2 "insert into xip_fixedconv values('TOWN-F', 'I', 'T', 'SO02', 2, '1', '', '报文标识', 'N', -1, -1, '0', 0, 0, '', '', '', '1', '1067')";
db2 "insert into xip_fixedconv values('TOWN-F', 'I', 'T', 'SO02', 3, '1', '', '接口类别', 'N', -1, -1, '0', 0, 0, '', '', '', '1', '0860')";
db2 "insert into xip_fixedconv values('TOWN-F', 'I', 'T', 'SO02', 4, '1', '', '接口代码', 'N', -1, -1, '0', 0, 0, '', '', '', '1', '154F')";
db2 "insert into xip_fixedconv values('TOWN-F', 'I', 'T', 'SO02', 5, '1', '', '交易发起域', 'N', -1, -1, '0', 0, 0, '', '', '', '1', '0710')";
db2 "insert into xip_fixedconv values('TOWN-F', 'I', 'T', 'SO02', 6, '1', '', '发送系统', 'N', -1, -1, '0', 0, 0, '', '', '', '1', '0730')";
db2 "insert into xip_fixedconv values('TOWN-F', 'I', 'T', 'SO02', 7, '1', '', '接收系统', 'N', -1, -1, '0', 0, 0, '', '', '', '1', '0290')";
db2 "insert into xip_fixedconv values('TOWN-F', 'I', 'T', 'SO02', 8, '1', '', '经办机构', 'N', -1, -1, '0', 0, 0, '', '', '', '1', '0280')";
db2 "insert into xip_fixedconv values('TOWN-F', 'I', 'T', 'SO02', 9, '1', '', '险种', 'N', -1, -1, '0', 0, 0, '', '', '', '1', '0220')";
db2 "insert into xip_fixedconv values('TOWN-F', 'I', 'T', 'SO02', 10, '1', '', '交易日期', 'N', -1, -1, '1', 0, 0, '', '', '', '1', '0440')";
db2 "insert into xip_fixedconv values('TOWN-F', 'I', 'T', 'SO02', 11, '1', '', '交易时间', 'N', -1, -1, '1', 0, 0, '', '', '', '1', '0450')";
db2 "insert into xip_fixedconv values('TOWN-F', 'I', 'T', 'SO02', 12, '1', '', '重发标志', 'N', -1, -1, '0', 0, 0, '', '', '', '1', '0670')";
db2 "insert into xip_fixedconv values('TOWN-F', 'I', 'T', 'SO02', 13, '1', '', '备用', 'N', -1, -1, '0', 0, 0, '', '', '', '1', '1510')";
db2 "insert into xip_fixedconv values('TOWN-F', 'I', 'T', 'SO02', 14, '1', '', '回盘文件名', 'N', -1, -1, '0', 0, 0, '', '', '', '1', '153G')";
db2 "insert into xip_fixedconv values('TOWN-F', 'I', 'T', 'SO02', 15, '1', '', '报盘笔数', 'N', -1, -1, '0', 0, 0, '', '', '', '1', '0520')";
db2 "insert into xip_fixedconv values('TOWN-F', 'I', 'T', 'SO02', 16, '1', '', '经办人', 'N', -1, -1, '0', 0, 0, '', '', '', '1', '0810')";
db2 "insert into xip_fixedconv values('TOWN-F', 'I', 'T', 'SO02', 17, '1', '', '银行代码', 'N', -1, -1, '0', 0, 0, '', '', '', '1', '170Y')";
db2 "insert into xip_fixedconv values('TOWN-F', 'I', 'T', 'SO02', 18, '1', '', '报盘文件名', 'N', -1, -1, '0', 0, 0, '', '', '', '1', '170S')";
db2 "insert into xip_fixedconv values('TOWN-F', 'I', 'T', 'SO02', 19, '1', '', '批次号', 'N', -1, -1, '0', 0, 0, '', '', '', '1', '0300')";
db2 "insert into xip_fixedconv values('TOWN-F', 'O', 'T', 'SO02', 1, '0', '0580', '版本', 'N', -1, -1, '0', 0, 0, '', '', '', '2', '')";
db2 "insert into xip_fixedconv values('TOWN-F', 'O', 'T', 'SO02', 2, '0', '1067', '报文标识', 'N', -1, -1, '0', 0, 0, '', '', '', '2', '')";
db2 "insert into xip_fixedconv values('TOWN-F', 'O', 'T', 'SO02', 3, '0', '0860', '接口类别', 'N', -1, -1, '0', 0, 0, '', '', '', '2', '')";
db2 "insert into xip_fixedconv values('TOWN-F', 'O', 'T', 'SO02', 4, '0', '154F', '接口代码', 'N', -1, -1, '0', 0, 0, '', '', '', '2', '')";
db2 "insert into xip_fixedconv values('TOWN-F', 'O', 'T', 'SO02', 5, '0', '0710', '交易发起域', 'N', -1, -1, '0', 0, 0, '', '', '', '2', '')";
db2 "insert into xip_fixedconv values('TOWN-F', 'O', 'T', 'SO02', 6, '0', '0730', '发送系统', 'N', -1, -1, '0', 0, 0, '', '', '', '2', '')";
db2 "insert into xip_fixedconv values('TOWN-F', 'O', 'T', 'SO02', 7, '0', '0290', '接收系统', 'N', -1, -1, '0', 0, 0, '', '', '', '2', '')";
db2 "insert into xip_fixedconv values('TOWN-F', 'O', 'T', 'SO02', 8, '0', '0280', '统筹区划代码', 'N', -1, -1, '0', 0, 0, '', '', '', '2', '')";
db2 "insert into xip_fixedconv values('TOWN-F', 'O', 'T', 'SO02', 9, '0', '0220', '险种', 'N', -1, -1, '0', 0, 0, '', '', '', '2', '')";
db2 "insert into xip_fixedconv values('TOWN-F', 'O', 'T', 'SO02', 10, '0', '0440', '交易日期', 'N', -1, -1, '0', 0, 0, '', '', '', '2', '')";
db2 "insert into xip_fixedconv values('TOWN-F', 'O', 'T', 'SO02', 11, '0', '0450', '交易时间', 'N', -1, -1, '0', 0, 0, '', '', '', '2', '')";
db2 "insert into xip_fixedconv values('TOWN-F', 'O', 'T', 'SO02', 12, '0', '0670', '重发标志', 'N', -1, -1, '0', 0, 0, '', '', '', '2', '')";
db2 "insert into xip_fixedconv values('TOWN-F', 'O', 'T', 'SO02', 13, '0', '1350', '交易返回码', 'N', -1, -1, '0', 0, 0, '', '', '', '2', '')";
db2 "insert into xip_fixedconv values('TOWN-F', 'O', 'T', 'SO02', 14, '0', '0004', '业务返回码', 'N', -1, -1, '0', 0, 0, '', '', '', '2', '')";
db2 "insert into xip_fixedconv values('TOWN-F', 'O', 'T', 'SO02', 15, '0', '0005', '返回信息', 'N', -1, -1, '0', 0, 0, '', '', '', '2', '')";
db2 "insert into xip_fixedconv values('TOWN-F', 'O', 'T', 'SO02', 16, '0', '1510', '备用', 'N', -1, -1, '0', 0, 0, '', '', '', '2', '')";
db2 "delete from xip_chnlroute where xip_id='TOWN-F' and xip_fromtrcode='SO02'";
db2 "insert into xip_chnlroute values('TOWN-F', 'SO02', 1, 'ROUTE', 'TOWN-T', 'SO02-1', '', '', 'N')";
db2 "delete from xip_tradeflow where xip_id='TOWN-T' and xip_flowcode='SO02-1'";
db2 "insert into xip_tradeflow values('TOWN-T', 'SO02-1', 1, 'CALL', 'libkftpflow.so', 'KFtpFlow', '', '')";
db2 "delete from xip_tradfuncio where xip_id='TOWN-T' and xip_flowcode='SO02-1' and xip_seq=1";
db2 "insert into xip_tradfuncio values('TOWN-T', 'SO02-1', 1, 1, '#TOWN-NSOCIHP', 'P0020', 'I', 'ftpid')";
db2 "insert into xip_tradfuncio values('TOWN-T', 'SO02-1', 1, 2, '#N', 'P0720', 'I', '是否执行所有Y-是N-否')";
db2 "insert into xip_chnlroute values('TOWN-F', 'SO02', 2, 'IF', 'P0004', '==', '#0000', '', 'N')";
db2 "insert into xip_chnlroute values('TOWN-F', 'SO02', 3, 'ROUTE', 'NSOCI-T', 'SO02-2', '', '', 'N')";
db2 "delete from xip_tradeflow where xip_id='NSOCI-T' and xip_flowcode='SO02-2'";
db2 "insert into xip_tradeflow values('NSOCI-T', 'SO02-2', 1, 'CALL', 'libnsocipub.so', 'NsociGetCityParm', '', '')";
db2 "delete from xip_tradfuncio where xip_id='NSOCI-T' and xip_flowcode='SO02-2' and xip_seq=1";
db2 "insert into xip_tradfuncio values('NSOCI-T', 'SO02-2', 1, 11, 'P1094', 'P1094', 'O', 'KEY')";
db2 "insert into xip_tradfuncio values('NSOCI-T', 'SO02-2', 1, 12, 'P1095', 'P1095', 'O', '加解密本地文件路径')";
db2 "insert into xip_tradfuncio values('NSOCI-T', 'SO02-2', 1, 3, 'P0300', 'P0300', 'I', '批次号')";
db2 "insert into xip_tradfuncio values('NSOCI-T', 'SO02-2', 1, 4, '#H', 'P0690', 'I', '报盘回盘标志')";
db2 "insert into xip_tradfuncio values('NSOCI-T', 'SO02-2', 1, 5, '#NSOCI_SFTP', 'P0870', 'I', 'SFTP_ID(固定值)')";
db2 "insert into xip_tradfuncio values('NSOCI-T', 'SO02-2', 1, 6, 'P1016', 'P1016', 'O', '用户密码')";
db2 "insert into xip_tradfuncio values('NSOCI-T', 'SO02-2', 1, 7, 'P1036', 'P1036', 'O', 'sftp本地路径')";
db2 "insert into xip_tradfuncio values('NSOCI-T', 'SO02-2', 1, 8, 'P1037', 'P1037', 'O', 'sftp远程路径')";
db2 "insert into xip_tradfuncio values('NSOCI-T', 'SO02-2', 1, 9, 'P1054', 'P1054', 'O', '系统标志（锦州市|村镇）')";
db2 "insert into xip_tradfuncio values('NSOCI-T', 'SO02-2', 1, 10, 'P1074', 'P1074', 'O', 'IP')";
db2 "insert into xip_tradfuncio values('NSOCI-T', 'SO02-2', 1, 13, 'P1143', 'P1143', 'O', '端口')";
db2 "insert into xip_tradfuncio values('NSOCI-T', 'SO02-2', 1, 14, 'P1193', 'P1193', 'O', '用户名')";
db2 "insert into xip_tradfuncio values('NSOCI-T', 'SO02-2', 1, 15, 'P170S', 'P170S', 'O', '报盘文件名')";
db2 "insert into xip_tradeflow values('NSOCI-T', 'SO02-2', 2, 'CALL', 'libnsocipub.so', 'NsociSftpUse', '', '')";
db2 "delete from xip_tradfuncio where xip_id='NSOCI-T' and xip_flowcode='SO02-2' and xip_seq=2";
db2 "insert into xip_tradfuncio values('NSOCI-T', 'SO02-2', 2, 25, 'P153G', 'P153G', 'I', '远程文件名')";
db2 "insert into xip_tradfuncio values('NSOCI-T', 'SO02-2', 2, 26, 'P1606', 'P1606', 'I', '分类文件路径')";
db2 "insert into xip_tradfuncio values('NSOCI-T', 'SO02-2', 2, 27, 'P153G', 'P170S', 'I', '本地文件名')";
db2 "insert into xip_tradfuncio values('NSOCI-T', 'SO02-2', 2, 16, 'P0300', 'P0300', 'I', '批次号')";
db2 "insert into xip_tradfuncio values('NSOCI-T', 'SO02-2', 2, 17, 'P1016', 'P1016', 'I', '密码')";
db2 "insert into xip_tradfuncio values('NSOCI-T', 'SO02-2', 2, 19, '#T', 'P102a', 'I', '上下传标志')";
db2 "insert into xip_tradfuncio values('NSOCI-T', 'SO02-2', 2, 20, 'P1036', 'P1036', 'I', '本地路径')";
db2 "insert into xip_tradfuncio values('NSOCI-T', 'SO02-2', 2, 21, 'P1037', 'P1037', 'I', '远程路径')";
db2 "insert into xip_tradfuncio values('NSOCI-T', 'SO02-2', 2, 18, '#nsocihp', 'P102A', 'I', '脚本名')";
db2 "insert into xip_tradfuncio values('NSOCI-T', 'SO02-2', 2, 23, 'P1143', 'P1143', 'I', '端口')";
db2 "insert into xip_tradfuncio values('NSOCI-T', 'SO02-2', 2, 22, 'P1074', 'P1074', 'I', 'IP地址')";
db2 "insert into xip_tradfuncio values('NSOCI-T', 'SO02-2', 2, 24, 'P1193', 'P1193', 'I', '用户名')";
db2 "insert into xip_tradeflow values('NSOCI-T', 'SO02-2', 3, 'IF', 'P0004', '==', '#0000', '')";
db2 "insert into xip_tradeflow values('NSOCI-T', 'SO02-2', 4, 'COMM', '522202-T', '', 'B', '新社保回盘')";
db2 "delete from xip_xmlconv where xip_id='NSOCI-T' and xip_convlevel='T' and xip_trcode='522202-T'";
db2 "delete from xip_xmlnodeattr where xip_id='NSOCI-T' and xip_convlevel='T' and xip_trcode='522202-T'";
db2 "insert into xip_xmlconv values('NSOCI-T', 'I', 'T', '522202-T', 0, '', 'Root', '根节点', 'N', '/Root/*', 'R', 'M', 'N', '', 'N', 'N', 'N', '', 'G1ToU', '0', 0, 0, '', '', '', '0')";
db2 "insert into xip_xmlconv values('NSOCI-T', 'I', 'T', '522202-T', 1, 'Root', 'head', '报文头', 'N', '/Root/head/*', 'M', 'M', 'N', '', 'N', 'N', 'N', '', 'UToG1', '0', 0, 0, '', '', '', '0')";
db2 "insert into xip_xmlconv values('NSOCI-T', 'I', 'T', '522202-T', 2, 'head', 'version', '版本', 'N', '/Root/head/version', 'B', 'M', 'N', '', 'N', 'N', 'N', '0580', 'UToG1', '0', 0, 0, '', '', '', '1')";
db2 "insert into xip_xmlconv values('NSOCI-T', 'I', 'T', '522202-T', 3, 'head', 'ref', '报文标识', 'N', '/Root/head/ref', 'B', 'M', 'N', '', 'N', 'N', 'N', '1067', 'UToG1', '0', 0, 0, '', '', '', '1')";
db2 "insert into xip_xmlconv values('NSOCI-T', 'I', 'T', '522202-T', 4, 'head', 'sysCode', '接口类别', 'N', '/Root/head/sysCode', 'B', 'M', 'N', '', 'N', 'N', 'N', '0860', 'UToG1', '0', 0, 0, '', '', '', '1')";
db2 "insert into xip_xmlconv values('NSOCI-T', 'I', 'T', '522202-T', 5, 'head', 'busCode', '接口代码', 'N', '/Root/head/busCode', 'B', 'M', 'N', '', 'N', 'N', 'N', '154F', 'UToG1', '0', 0, 0, '', '', '', '1')";
db2 "insert into xip_xmlconv values('NSOCI-T', 'I', 'T', '522202-T', 6, 'head', 'tradeSrc', '交易发起域', 'N', '/Root/head/tradeSrc', 'B', 'M', 'N', '', 'N', 'N', 'N', '0710', 'UToG1', '0', 0, 0, '', '', '', '1')";
db2 "insert into xip_xmlconv values('NSOCI-T', 'I', 'T', '522202-T', 7, 'head', 'sender', '发送系统', 'N', '/Root/head/sender', 'B', 'M', 'N', '', 'N', 'N', 'N', '0730', 'UToG1', '0', 0, 0, '', '', '', '1')";
db2 "insert into xip_xmlconv values('NSOCI-T', 'I', 'T', '522202-T', 8, 'head', 'reciver', '接收系统', 'N', '/Root/head/reciver', 'B', 'M', 'N', '', 'N', 'N', 'N', '0290', 'UToG1', '0', 0, 0, '', '', '', '1')";
db2 "insert into xip_xmlconv values('NSOCI-T', 'I', 'T', '522202-T', 9, 'head', 'aaa027', '统筹区划代码', 'N', '/Root/head/aaa027', 'B', 'M', 'N', '', 'N', 'N', 'N', '0280', 'UToG1', '0', 0, 0, '', '', '', '1')";
db2 "insert into xip_xmlconv values('NSOCI-T', 'I', 'T', '522202-T', 10, 'head', 'aae140', '险种', 'N', '/Root/head/aae140', 'B', 'M', 'N', '', 'N', 'N', 'N', '0220', 'UToG1', '0', 0, 0, '', '', '', '1')";
db2 "insert into xip_xmlconv values('NSOCI-T', 'I', 'T', '522202-T', 11, 'head', 'date', '交易日期', 'N', '/Root/head/date', 'B', 'M', 'N', '', 'N', 'N', 'N', '0440', 'UToG1', '0', 0, 0, '', '', '', '1')";
db2 "insert into xip_xmlconv values('NSOCI-T', 'I', 'T', '522202-T', 12, 'head', 'time', '交易时间', 'N', '/Root/head/time', 'B', 'M', 'N', '', 'N', 'N', 'N', '0450', 'UToG1', '0', 0, 0, '', '', '', '1')";
db2 "insert into xip_xmlconv values('NSOCI-T', 'I', 'T', '522202-T', 13, 'head', 'reSnd', '重发标志', 'N', '/Root/head/reSnd', 'B', 'M', 'N', '', 'N', 'N', 'N', '0670', 'UToG1', '0', 0, 0, '', '', '', '1')";
db2 "insert into xip_xmlconv values('NSOCI-T', 'I', 'T', '522202-T', 14, 'head', 'rst', '返回结果', 'N', '/Root/head/rst/*', 'M', 'M', 'N', '', 'N', 'N', 'N', '', 'UToG1', '0', 0, 0, '', '', '', '0')";
db2 "insert into xip_xmlconv values('NSOCI-T', 'I', 'T', '522202-T', 15, 'rst', 'tradeCode', '交易返回码', 'N', '/Root/head/rst/tradeCode', 'B', 'M', 'N', '', 'N', 'N', 'N', '1350', 'UToG1', '0', 0, 0, '', '', '', '1')";
db2 "insert into xip_xmlconv values('NSOCI-T', 'I', 'T', '522202-T', 16, 'rst', 'busiCode', '业务返回码', 'N', '/Root/head/rst/busiCode', 'B', 'M', 'N', '', 'N', 'N', 'N', '0004', 'UToG1', '0', 0, 0, '', '', '', '1')";
db2 "insert into xip_xmlconv values('NSOCI-T', 'I', 'T', '522202-T', 17, 'rst', 'info', '返回信息', 'N', '/Root/head/rst/info', 'B', 'M', 'N', '', 'N', 'N', 'N', '0005', 'UToG1', '0', 0, 0, '', '', '', '1')";
db2 "insert into xip_xmlconv values('NSOCI-T', 'I', 'T', '522202-T', 18, 'head', 'by', '备用', 'N', '/Root/head/by', 'B', 'M', 'N', '', 'N', 'N', 'N', '1510', 'UToG1', '0', 0, 0, '', '', '', '1')";
db2 "insert into xip_xmlconv values('NSOCI-T', 'O', 'T', '522202-T', 0, '', 'head', 'head', 'N', '/head/*', 'R', 'M', 'N', '', 'N', 'N', 'N', '', 'NOT', '0', 0, 0, '', '', '', '0')";
db2 "insert into xip_xmlconv values('NSOCI-T', 'O', 'T', '522202-T', 1, 'head', 'version', 'version', 'N', '/head/version', 'B', 'M', 'N', '', 'N', 'N', 'N', '0580', 'G1ToU', '0', 0, 0, '', '', '', '1')";
db2 "insert into xip_xmlconv values('NSOCI-T', 'O', 'T', '522202-T', 2, 'head', 'ref', 'ref', 'N', '/head/ref', 'B', 'M', 'N', '', 'N', 'N', 'N', '1067', 'G1ToU', '0', 0, 0, '', '', '', '1')";
db2 "insert into xip_xmlconv values('NSOCI-T', 'O', 'T', '522202-T', 3, 'head', 'sysCode', 'sysCode', 'N', '/head/sysCode', 'B', 'M', 'N', '', 'N', 'N', 'N', '0860', 'G1ToU', '0', 0, 0, '', '', '', '1')";
db2 "insert into xip_xmlconv values('NSOCI-T', 'O', 'T', '522202-T', 4, 'head', 'busCode', 'busCode', 'N', '/head/busCode', 'B', 'M', 'N', '', 'N', 'N', 'N', '154F', 'G1ToU', '0', 0, 0, '', '', '', '1')";
db2 "insert into xip_xmlconv values('NSOCI-T', 'O', 'T', '522202-T', 5, 'head', 'tradeSrc', 'tradeSrc', 'N', '/head/tradeSrc', 'B', 'M', 'N', '', 'N', 'N', 'N', '0710', 'G1ToU', '0', 0, 0, '', '', '', '1')";
db2 "insert into xip_xmlconv values('NSOCI-T', 'O', 'T', '522202-T', 6, 'head', 'sender', 'sender', 'N', '/head/sender', 'B', 'M', 'N', '', 'N', 'N', 'N', '0730', 'G1ToU', '0', 0, 0, '', '', '', '1')";
db2 "insert into xip_xmlconv values('NSOCI-T', 'O', 'T', '522202-T', 7, 'head', 'reciver', 'reciver', 'N', '/head/reciver', 'B', 'M', 'N', '', 'N', 'N', 'N', '0290', 'G1ToU', '0', 0, 0, '', '', '', '1')";
db2 "insert into xip_xmlconv values('NSOCI-T', 'O', 'T', '522202-T', 8, 'head', 'aaa027', 'aaa027', 'N', '/head/aaa027', 'B', 'M', 'N', '', 'N', 'N', 'N', '0280', 'G1ToU', '0', 0, 0, '', '', '', '1')";
db2 "insert into xip_xmlconv values('NSOCI-T', 'O', 'T', '522202-T', 9, 'head', 'aae140', 'aae140', 'N', '/head/aae140', 'B', 'M', 'N', '', 'N', 'N', 'N', '0220', 'G1ToU', '0', 0, 0, '', '', '', '1')";
db2 "insert into xip_xmlconv values('NSOCI-T', 'O', 'T', '522202-T', 10, 'head', 'date', 'date', 'N', '/head/date', 'B', 'M', 'N', '', 'N', 'N', 'N', '0440', 'G1ToU', '0', 0, 0, '', '', '', '1')";
db2 "insert into xip_xmlconv values('NSOCI-T', 'O', 'T', '522202-T', 11, 'head', 'time', 'time', 'N', '/head/time', 'B', 'M', 'N', '', 'N', 'N', 'N', '0450', 'G1ToU', '0', 0, 0, '', '', '', '1')";
db2 "insert into xip_xmlconv values('NSOCI-T', 'O', 'T', '522202-T', 12, 'head', 'reSnd', 'reSnd', 'N', '/head/reSnd', 'B', 'M', 'N', '', 'N', 'N', 'N', '0670', 'G1ToU', '0', 0, 0, '', '', '', '1')";
db2 "insert into xip_xmlconv values('NSOCI-T', 'O', 'T', '522202-T', 13, 'head', 'rst', 'rst', 'N', '/head/rst/*', 'M', 'M', 'N', '', 'N', 'N', 'N', '', 'G1ToU', '0', 0, 0, '', '', '', '0')";
db2 "insert into xip_xmlconv values('NSOCI-T', 'O', 'T', '522202-T', 14, 'rst', 'tradeCode', 'tradeCode', 'N', '/head/rst/tradeCode', 'B', 'M', 'N', '', 'N', 'N', 'N', '1350', 'G1ToU', '0', 0, 0, '', '', '', '1')";
db2 "insert into xip_xmlconv values('NSOCI-T', 'O', 'T', '522202-T', 15, 'rst', 'busiCode', 'busiCode', 'N', '/head/rst/busiCode', 'B', 'M', 'N', '', 'N', 'N', 'N', '0004', 'G1ToU', '0', 0, 0, '', '', '', '1')";
db2 "insert into xip_xmlconv values('NSOCI-T', 'O', 'T', '522202-T', 16, 'rst', 'info', 'info', 'N', '/head/rst/info', 'B', 'M', 'N', '', 'N', 'N', 'N', '0005', 'G1ToU', '0', 0, 0, '', '', '', '1')";
db2 "insert into xip_xmlconv values('NSOCI-T', 'O', 'T', '522202-T', 17, 'head', 'by', 'by', 'N', '/head/by', 'B', 'M', 'N', '', 'N', 'N', 'N', '1510', 'G1ToU', '0', 0, 0, '', '', '', '1')";
db2 "insert into xip_xmlconv values('NSOCI-T', 'O', 'T', '522202-T', 18, 'head', 'data', 'data', 'N', '/head/data/*', 'M', 'M', 'N', '', 'N', 'N', 'N', '', 'G1ToU', '0', 0, 0, '', '', '', '0')";
db2 "insert into xip_xmlconv values('NSOCI-T', 'O', 'T', '522202-T', 19, 'data', 'filename', 'filename', 'N', '/head/data/filename', 'B', 'M', 'N', '', 'N', 'N', 'N', '153G', 'G1ToU', '0', 0, 0, '', '', '', '1')";
db2 "insert into xip_xmlconv values('NSOCI-T', 'O', 'T', '522202-T', 20, 'data', 'fnumber', 'fnumber', 'N', '/head/data/fnumber', 'B', 'M', 'N', '', 'N', 'N', 'N', '0520', 'G1ToU', '0', 0, 0, '', '', '', '1')";
db2 "insert into xip_xmlconv values('NSOCI-T', 'O', 'T', '522202-T', 21, 'data', 'jbr', 'jbr', 'N', '/head/data/jbr', 'B', 'M', 'N', '', 'N', 'N', 'N', '0810', 'G1ToU', '0', 0, 0, '', '', '', '1')";
db2 "insert into xip_xmlconv values('NSOCI-T', 'O', 'T', '522202-T', 22, 'data', 'yhwd', 'yhwd', 'N', '/head/data/yhwd', 'B', 'M', 'N', '', 'N', 'N', 'N', '170Y', 'G1ToU', '0', 0, 0, '', '', '', '1')";
db2 "insert into xip_xmlconv values('NSOCI-T', 'O', 'T', '522202-T', 23, 'data', 'bpmc', 'bpmc', 'N', '/head/data/bpmc', 'B', 'M', 'N', '', 'N', 'N', 'N', '170S', 'G1ToU', '0', 0, 0, '', '', '', '1')";
db2 "insert into xip_tradeflow values('NSOCI-T', 'SO02-2', 5, 'ENDIF', '', '', '', '')";
db2 "insert into xip_chnlroute values('TOWN-F', 'SO02', 4, 'ENDIF', '', '', '', '', 'N')";

db2 connect reset
